### ISSUE TITLE
Provisioning

### ISSUE THREAD

**Issue by maedoc** [the-virtual-brain/tvb-recon#16]
The scripts for setting up a VM are out of date,

https://github.com/ins-amu/bnm-recon-tools/tree/master/docs/setup-vm

and could be rewritten for Ansible to improve robustness. It's probably a good idea for us to be using a Vagrant (VBox) or Docker VM where possible, so that at least across dev machines, the environment is identical:

- Vagrantfile provides a local VM so everyone's using the same environment
- same Ansible playbook used to setup VM & cluster env
- VM sets up environment on secondary (non-OS) disk so we can share to get quick started.

**Comment by maedoc** [comment]
Docker might be worth using as well: the whole thing is lightweight and flexible compared to Vagrant. Once the image is built, one can practically run one off commands 
```bash
docker run --rm -it tvb/recon -v /my_data:/work/data \
    /work/env/freesurfer/bin/recon-all -s test -i /work/data/t1.nii.gz -all
```
without having to run the VM all the time.

**Comment by maedoc** [comment]
And a a nice example of packaging FS inside a Docker container here

https://github.com/BIDS-Apps/freesurfer

where

- reduced size to ~6 GiB
- nice example of using a main Python script to parse args and run workflows inside the machine

**Comment by liadomide** [comment]
Docker image has been created for this project, so i close this.
