### ISSUE TITLE
Move datasets into an LFS

### ISSUE THREAD

**Issue by maedoc** [the-virtual-brain/tvb-recon#18]
Git doesn't handle large files well. This repo has a bunch of it; let's move it into a LFS store.

**Comment by maedoc** [comment]
Not sure if LFS is the best, but let's assume we have the data somewhere. What do we have?

- FreeSurfer default subjects
- TVB's T1 DWI datasets
- Clinical data with T1 DWI CT

Ideally, we get these organized so our CI runners can test our code on all of it.

Security challenge is that clinical data should only be run with code from people we trust. PRs from external sources can only be run on FS or TVB anon data, so check if GitLab can handle that.

**Comment by maedoc** [comment]
Looks like we could set up runners with different user names and permissions to isolate them better on the cluster.

**Comment by maedoc** [comment]
TVB's new dataset would weigh around 1.5 GiB. Clinical datasets will be bigger. I don't think handling them with Git is a good idea. Let's stick to custom, small images & files that can be efficiently stored by Git for automatic unit testing.

The test runner should do unit tests by default and, with certain arguments, test flows on different datasets. Snapshots can be added as artifacts. We need to see what other files we might want to artifact; GitLab CI has a limit on artifact size, but can be tuned.

**Comment by liadomide** [comment]
yep, clinical data is way larger, and not to be made public.
for test cases, very small artificially generated data should be enough.
for LFS should no longer be needed for this repo, at least not in the immediate future, so I close this issue.
