### ISSUE TITLE
rename package

### ISSUE THREAD

**Issue by maedoc** [the-virtual-brain/tvb-recon#24]
This repo might be better named & located as `the-virtual-brain/tvb-recon`, with code residing under the `tvb.recon` namespace. What do you think @dionperd @liadomide @popaula937 ?

**Comment by liadomide** [comment]
Sounds good to me.

**Comment by dionperd** [comment]
Same here. Who and when is going to do it?

**Comment by maedoc** [comment]
I'll do it after we merge you latest stuff.

**Comment by maedoc** [comment]
move is also done: update your remote: 
```bash
git remote rm origin
git remote add origin git@github.com:the-virtual-brain/tvb-recon
```
