### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by maedoc** [the-virtual-brain/tvb-recon#27]
This repo is largely undocumented. Getting new users up and running is a huge effort. Once the library and workflows have stabilized, we should set up Sphinx API docs, overview and worked examples.

**Comment by umarbrowser** [comment]
Hi, is there any one working on this bug? if not i will like to do it.

**Comment by liadomide** [comment]
Nobody is working on this at the moment. 
Your contribution would be welcome.
But, we can not offer much support or input, it would need to come from studying the existing code. Which might prove to be quite difficult. Do you think you can do it?

**Comment by umarbrowser** [comment]
Yes I can do it, I will try my best.
Right now i am available 24/7 that what makes me available to fix this bug, just gives me some feedback and tips.
