### ISSUE TITLE
Migrate TVB to support Python 3

### ISSUE THREAD

**Issue by umarbrowser** [the-virtual-brain/tvb-recon#46]
Hi there.

I came across some post on medium and  i saw that the python software foundation are going to stop supporting python 2 on 2020, Then i came with the idea why not start porting the virtual brain from now to start supporting the latest version of python 3.

Please core developers see that issue, I will like to offer my contribution.

@liadomide @bogdanneacsa @maedoc @pausz @twotribes @liadomide 

Thanks you.

References:
https://legacy.python.org/dev/peps/pep-0373/
https://pythonclock.org/

**Comment by maedoc** [comment]
hi Umar thanks for opening the issue.  This repo is in fact already Python 3. 

On the other hand, the simulator package has only a branch where we tested the `2to3` tool to move the code to Python 3, and the framework package is not yet Python 3 compatible. 

So, we are indeed aware. If you wish to contribute, it would be most useful for you to look at the tvb-library and tvb-framework packages, run `2to3` and get the test suites to pass on Python 3.

**Comment by umarbrowser** [comment]
Thanks @maedoc for replaying so quickly, I will start right away.
Please is there anything you can tell me before i can start, May be links or anything.

Thanks.

**Comment by liadomide** [comment]
As also mentioned above, tvb-recon module is already Python3. Thus, this issues should not be open here.
In fact tvb-recon requires python3, but because Pegasus is only Python2 compatible, 2 environments need to exist for this to fully work. This is only temporary, as Pegasus has as WIP migration to python3.

**Comment by umarbrowser** [comment]
Ok thanks, just count me in After anything goes normal under Pegasus migration to python3.
