### ISSUE TITLE
permission denied when running run_sequentially.py

### ISSUE THREAD

**Issue by zhengliuer** [the-virtual-brain/tvb-recon#69]
Hi, I pull the docker image, and successfully entered it. While when running run_seauentially.py, I've got this error:
![image](https://user-images.githubusercontent.com/65115609/121206778-5242bb80-c8ab-11eb-9d56-e04a7ce04815.png)
Could anyone help, please?

**Comment by zhengliuer** [comment]
Hi, I just ran ```sudo chmod 777 /home/submitter/data/TVB1``` and the error above disappeared. However, another one came out.
![image](https://user-images.githubusercontent.com/65115609/121207549-f62c6700-c8ab-11eb-9642-74c25b7255bc.png)

![image](https://user-images.githubusercontent.com/65115609/121207493-e876e180-c8ab-11eb-92e6-cf1f359137f8.png)

**Comment by popaula937** [comment]
Hi, could you attach a screenshot of the full command you are using in order to start the docker container?

**Comment by popaula937** [comment]
This seems to be a permission error as well. 
Try mounting the tvb-recon folder inside the docker image like this:
`$ docker run -it -v your_path_to_TVB_patients/TVB_patients/:/home/submitter/data -v your_path_to_tvb_recon/tvb-recon/:/opt/tvb-recon thevirtualbrain/tvb-recon /bin/bash`

If that does not help, please run inside the docker image: `sudo chmod 777 /opt/tvb-recon` before any other commands.

**Comment by zhengliuer** [comment]
Hi, the server is under repair. I'll get back to you as soon as possible.

**Comment by zhengliuer** [comment]
I ran the same command as the README gives me 
```docker run -it -v your_path_to_TVB_patients/TVB_patients/:/home/submitter/data -v your_path_to_tvb_recon/tvb-recon/:/opt/tvb-recon thevirtualbrain/tvb-recon /bin/bash```
And my  data is in /home/lz/TVB_patients, and tvb-recon is in /home/Projects/tvb-recon, so the command I typed is
```
sudo docker run -it -v  /home/lz/TVB_patients/:/home/submitter/data -v /home/Projects/tvb-recon/:/opt/tvb-recon thevirtualbrain/tvb-recon /bin/bash
```

**Comment by popaula937** [comment]
tvb-recon is generating some files in its own folder, so I suspect there is a similar permission problem with the **tvb-recon** folder as you had with the **data** folder.

**Comment by zhengliuer** [comment]
Hi, I do 
```
sudo chmod 777 /home/submitter/data/
sudo chmod 777 /opt/tvb-recon
```
and it starts to run.
While I've encountered this, I don't know if this is right.
![image](https://user-images.githubusercontent.com/65115609/121363055-2c7bec00-c969-11eb-82b8-f304abf1394a.png)
![image](https://user-images.githubusercontent.com/65115609/121363096-34d42700-c969-11eb-8764-816e2e3dc5d1.png)
it says ```monitord.done file was not generated yet!```
How do I know the code is running fine?

**Comment by popaula937** [comment]
This looks correct, the workflow started running and you should wait for it to finish the processing. It should take several hours, depending on your data. 
The _monitord.done_ file is generated only when the workflow is finished, so we track it and display this message as a status update.

Another way to track the progress is by opening a second terminal and enter the same container with the following command (you have to provide the correct container_id): `docker exec -i -t container_id /bin/bash`
Then run: `pegasus-status -l /home/submitter/pegasus/submit/submitter/pegasus/TVB-PIPELINE/run0001` 
It will display the status of the workflow (currently running jobs, how many are finished, whether some have errors etc).

Under the folder _TVB1/configs/dax_ you should see a file called _main_bnm.png_ with the diagram of all the jobs involved in the workflow, so you can get a sense of where the progress is.

**Comment by zhengliuer** [comment]
Thank you so much for your help! I really appreciate that!

**Comment by zhengliuer** [comment]
![image](https://user-images.githubusercontent.com/65115609/121368300-8e3e5500-c96d-11eb-905b-99ef4c0ac444.png)
I've got this. I think I need to focus on the FAILD and %Done.

**Comment by popaula937** [comment]
Yes, also check the STATE and expect the _recon_ID00._. job to take most of the execution time.

**Comment by zhengliuer** [comment]
May I ask what does the fifth and seventh lines of the screenshot mean? It says error from slot@container_id:

**Comment by popaula937** [comment]
Not sure, could you attach a screenshot of your input data folder?

**Comment by zhengliuer** [comment]
submitters/data/TVB1/raw/mri is like this
![image](https://user-images.githubusercontent.com/65115609/121373441-a7e19b80-c971-11eb-94e8-d3cb8bb32815.png)
submitters/data/TVB1/configs is like this
![image](https://user-images.githubusercontent.com/65115609/121373525-b92aa800-c971-11eb-8368-47f9bdabb5f2.png)

**Comment by popaula937** [comment]
Looks good, let's see how the processing goes.

**Comment by zhengliuer** [comment]
All right! Thanks!

**Comment by zhengliuer** [comment]
Hi, bad news.
![image](https://user-images.githubusercontent.com/65115609/121375568-68b44a00-c973-11eb-85ca-b23401f956ae.png)
Two FAILs

**Comment by zhengliuer** [comment]
It still keeps turning to run0002

**Comment by zhengliuer** [comment]
run002 says 
```
 STARTER at 172.17.0.2 failed to send file(s) to <172.17.0.2:34557>: error reading from /var/lib/condor/execute/dir_2285/dwi_input.mif: (errno..
Summary: 3 Condor jobs total (R:1 H:2)
```
While, maybe another permission problem?

**Comment by zhengliuer** [comment]
Bad news, the processing stopped when running002 finished, and it seems there're the same errors in run001 and run002 as above. Also. no output directory in TVB1 directory. I did see a output directory in tvb-recon with tvb.log in it.
This is the run002 part. 
![image](https://user-images.githubusercontent.com/65115609/121387516-50492d00-c97d-11eb-9f76-88896ffdfc8b.png)
I don't understand, I suppose there should be only one run00x, which is run001.

**Comment by popaula937** [comment]
There are 2 jobs launched for each patient to compute the data based on 2 brain atlases, the second job usually takes less time.

In order to investigate the issue, please send me the content of the following log files:
/home/submitter/pegasus/submit/submitter/pegasus/TVB-PIPELINE/run0001/00/00/mrconvert_ID0000009.out
/home/submitter/pegasus/submit/submitter/pegasus/TVB-PIPELINE/run0001/00/00/recon_ID0000001.out

**Comment by zhengliuer** [comment]
https://drive.google.com/file/d/1bIGC9CDWZGTflX6X5i65RRlNEa7bEmh0/view?usp=sharing
I upload it to Google Drive

**Comment by popaula937** [comment]
Could you also add:
/home/submitter/pegasus/submit/submitter/pegasus/TVB-PIPELINE/run0001/00/00/recon_ID0000001.out
?

**Comment by zhengliuer** [comment]
I'm sorry, my bad. Here it is
https://drive.google.com/file/d/1VTeHsJH-GNw0oZHjff0FxrcKOjDNYRqP/view?usp=sharing

**Comment by popaula937** [comment]
From the log files, it seems there are some issues with your data. Is it possible that the files were truncated? Please double-check them before running tvb-recon. 

Basic tests you could do inside the docker container to check the files are correct:
```
export PATH=$PATH:/opt/freesurfer-stable/freesurfer/bin/:/opt/mrtrix3/bin/
mrconvert /home/submitter/data/TVB1/raw/mri/dwi_raw.nii dwi.mif
mri_convert /home/submitter/data/TVB1/raw/mri/t1_input.nii.gz 001.mgz
```

These are the steps that fail during the workflow, and if your run them now, you should see the following error messages:
mrconvert: _[ERROR] file "/home/submitter/data/TVB1/raw/mri/dwi_raw.nii" is smaller than expected_
mri_convert: _error reading header from /home/submitter/data/TVB1/raw/mri/t1_input.nii.gz_

**Comment by zhengliuer** [comment]
Yes! I've reproduced the error. And this is what mrinfo gave me
![image](https://user-images.githubusercontent.com/65115609/121482602-e160e800-c9ff-11eb-85b4-87b4a9054a92.png)
The T1 was in DICOM. And DTI was in a DICOMDIR.  I've found this software called MRIcroGL, so I used it to convert DICOMDIR to nii. It seems that the result is not good enough. And I used this to convert T1, too. Looks like they both have some issues.
So do you have standard ways to convert DICOMDIR to nii?

**Comment by popaula937** [comment]
Users usually have the data prepared in Nifti format, so not sure what to recommend. Have you looked into Mrtrix for DTI and Freesurfer for T1 utilities? I think mrconvert and mri_convert also convert fom DICOM to Nifti.

**Comment by zhengliuer** [comment]
It is common to convert DICOM to Nifti, but DICOMDIR is hard to deal with. I've looked into MRtrix3, it doesn't support convert DICOMDIR to Nifti. Freesurfer might be able to do that. I'll give it a try.

**Comment by zhengliuer** [comment]
OK, I used freesurfer to convert the data, these works fine
```
export PATH=$PATH:/opt/freesurfer-stable/freesurfer/bin/:/opt/mrtrix3/bin/
mrconvert /home/submitter/data/TVB1/raw/mri/dwi_raw.nii dwi.mif
mri_convert /home/submitter/data/TVB1/raw/mri/t1_input.nii.gz 001.mgz
```

**Comment by zhengliuer** [comment]
Hi, do you know about this?https://github.com/HuifangWang/VEP_atlas_shared
Is this atlas available in tvb-recon

**Comment by popaula937** [comment]
> Hi, do you know about this?https://github.com/HuifangWang/VEP_atlas_shared
> Is this atlas available in tvb-recon

No, tvb-recon only works with Desikan-Killiany and Desterieux atlases.

**Comment by popaula937** [comment]
> OK, I used freesurfer to convert the data, these works fine
> 
> ```
> export PATH=$PATH:/opt/freesurfer-stable/freesurfer/bin/:/opt/mrtrix3/bin/
> mrconvert /home/submitter/data/TVB1/raw/mri/dwi_raw.nii dwi.mif
> mri_convert /home/submitter/data/TVB1/raw/mri/t1_input.nii.gz 001.mgz
> ```

Great, have you tried to run the workflow again on these files?

**Comment by zhengliuer** [comment]
I'm still trying, for I used the old bvec and bval files, one FAIL showed up. 
And remedy a mistake, I used MRtrix's command ```mrconvert``` to convert the DICOMDIR to nifti. 
Now I use that to generate new bvec and bval files and try again.

**Comment by zhengliuer** [comment]
btw, the %DONE should gradually become bigger, right? Not stuck at 7 or 8 for a long time.
![image](https://user-images.githubusercontent.com/65115609/121521395-97d7c380-ca26-11eb-822a-41bf89091c0f.png)
It has become like this for a very long time

**Comment by zhengliuer** [comment]
Hi, the T1 and DWI come from different machines.  The DWI is in a DICOMDIR, and in DICOMDIR, there're a lot of series. I think it might be safe to use the images from the same machines.. But there're two structural series: ti_mpr and t2_spc. Which one should I use?

**Comment by popaula937** [comment]
> btw, the %DONE should gradually become bigger, right? Not stuck at 7 or 8 for a long time.
> ![image](https://user-images.githubusercontent.com/65115609/121521395-97d7c380-ca26-11eb-822a-41bf89091c0f.png)
> It has become like this for a very long time

As long as the `recon` job is running, the progress will be stuck at the same value.

**Comment by popaula937** [comment]
> Hi, the T1 and DWI come from different machines. The DWI is in a DICOMDIR, and in DICOMDIR, there're a lot of series. I think it might be safe to use the images from the same machines.. But there're two structural series: ti_mpr and t2_spc. Which one should I use?

I cannot help much with the data, only with the workflow.

**Comment by zhengliuer** [comment]
Hi, one FAIL of the brand new data
here is the log
https://drive.google.com/file/d/1qa8I5aSnA5-_8TAuOAZiU0tG1XwzM-6f/view?usp=sharing
