### ISSUE TITLE
dwipreproc: [ERROR] Command failed: eddy_openmp ... Data not shelled

### ISSUE THREAD

**Issue by newton1985** [the-virtual-brain/tvb-recon#71]
Hi tvb-recon developers,

I'm having an issue with dwi preprocessing, where the program fails on a call to eddy_openmp. In particular, the output of the failed command is: 
eddy: msg=ECScanManager::GetShellIndicies: Data not shelled

I've attached the output file that contains the error message. Would you have a suggestion for a fix/workaround?
-Taylor

[dwipreproc_ID0000010.out.000.txt](https://github.com/the-virtual-brain/tvb-recon/files/7511173/dwipreproc_ID0000010.out.000.txt)

**Comment by maedoc** [comment]
Assuming your data is single or multishelled, you might need to add a flag to tell eddy_openmp that: 

   https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/eddy/UsersGuide#A--data_is_shelled

**Comment by newton1985** [comment]
Hi Marmaduke,

Thanks for your reply/suggestion. Indeed, I saw this in several forums online, but I'm not sure where in tvb-recon I should insert the "--data_is_shelled" flag. I tried adding it in docs/bin/dwi_preproc.sh, but that didn't work. Would you be willing to point me to the correct file?

-Taylor

**Comment by maedoc** [comment]
If I understand correctly (as I did not implement the current Pegasus DAX implementation), it should be added as an argument [here](https://github.com/the-virtual-brain/tvb-recon/blob/master/tvb/recon/dax/dwi_processing.py#L71).  These arguments are to the [dwipreproc](https://mrtrix.readthedocs.io/en/3.0_rc1/reference/scripts/dwipreproc.html) command of MRtrix3, which has a flag `-eddy_options`, e.g. `-eddy_options '--data_is_shelled'`.  If you are able, I would suggest trying this by hand first before changing the pipeline implementation.

**Comment by liadomide** [comment]
I close this, due to lack of activity
