### ISSUE TITLE
run_sequentially.py Error

### ISSUE THREAD

**Issue by nana-zhang** [the-virtual-brain/tvb-recon#72]
Hello, I'm running run_ sequentially. py, but I didn't use docker. I installed the required environment according to the requirements, but the following errors occurred. Can anyone help me?
![Screenshot from 2022-02-10 16-39-33](https://user-images.githubusercontent.com/70929994/153406558-5bd1af3c-570f-4d43-88e4-c07480df07a7.png)

**Comment by popaula937** [comment]
Hello, what is the reason for avoiding docker? 

Theoretically, tvb-recon could be used without docker, but there are certain changes that need to be done to the code, and also, you would have to be careful about the versions/compatibility of the tools it depends on.
In order to help with this error, I would need more details about your configuration, code changes (if any) and patient folder structure.

But, if it is possible for you to use docker, I would suggest you to try a first run with docker, in order to validate that tvb-recon works on your data and it generates the results you expect. And afterwards, we can debug the issues outside docker, but at least we would have a validation that tvb-recon works as expected in your case.

**Comment by nana-zhang** [comment]
Thank you for your reply and suggestion. I will try to use docker




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "the-virtual-brain/tvb-recon"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月11日(星期五) 晚上10:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [the-virtual-brain/tvb-recon] run_sequentially.py Error (Issue #72)





 
Hello, what is the reason for avoiding docker?
 
Theoretically, tvb-recon could be used without docker, but there are certain changes that need to be done to the code, and also, you would have to be careful about the versions/compatibility of the tools it depends on.
 In order to help with this error, I would need more details about your configuration, code changes (if any) and patient folder structure.
 
But, if it is possible for you to use docker, I would suggest you to try a first run with docker, in order to validate that tvb-recon works on your data and it generates the results you expect. And afterwards, we can debug the issues outside docker, but at least we would have a validation that tvb-recon works as expected in your case.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by nana-zhang** [comment]
Hello, I'm running tvb-recon with docker. I use git clone to download the code locally. The saved path is / home / nana / downloads /tvb-recon. The patient folder structure is also constructed according to the requirements of readme. The saved path is / home / nana / downloads / TVB_ Patients,I pull the docker image,and successfully entered it, but when I&nbsp;&nbsp;cd pegasus, no such file or directory is displayed, and the local folder exists in this folder,&nbsp; Can you help me see what's wrong?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "the-virtual-brain/tvb-recon"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月11日(星期五) 晚上10:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [the-virtual-brain/tvb-recon] run_sequentially.py Error (Issue #72)





 
Hello, what is the reason for avoiding docker?
 
Theoretically, tvb-recon could be used without docker, but there are certain changes that need to be done to the code, and also, you would have to be careful about the versions/compatibility of the tools it depends on.
 In order to help with this error, I would need more details about your configuration, code changes (if any) and patient folder structure.
 
But, if it is possible for you to use docker, I would suggest you to try a first run with docker, in order to validate that tvb-recon works on your data and it generates the results you expect. And afterwards, we can debug the issues outside docker, but at least we would have a validation that tvb-recon works as expected in your case.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by nana-zhang** [comment]
Hello, I'm running tvb-recon with docker. I use git clone to download the code locally. The saved path is / home / nana / downloads /tvb-recon. The patient folder structure is also constructed according to the requirements of readme. The saved path is / home / nana / downloads / TVB_ Patients,I pull the docker image,and successfully entered it, but when I  cd pegasus, no such file or directory is displayed, and the local folder exists in this folder,  Can you help me see what's wrong
![Screenshot from 2022-02-13 16-35-48](https://user-images.githubusercontent.com/70929994/153805791-9abd6464-2bdd-405a-a6f7-bb5b370d1948.png)
?

**Comment by liadomide** [comment]
I close this, ad #73 was open as followup
