### ISSUE TITLE
bash: cd:pegasus: No such file or directory

### ISSUE THREAD

**Issue by nana-zhang** [the-virtual-brain/tvb-recon#73]
Hello, I'm running tvb-recon with docker. I use git clone to download the code locally. The saved path is / home / nana / downloads /tvb-recon. The patient folder structure is also constructed according to the requirements of readme. The saved path is / home / nana / downloads / TVB_ Patients,I pull the docker image,and successfully entered it, but when I  cd pegasus, no such file or directory is displayed, and the local folder exists in this folder,  Can you help me see what's wrong
![Screenshot from 2022-02-13 16-35-48](https://user-images.githubusercontent.com/70929994/153805880-f44cabc3-4549-4598-bb94-1b3532890c5b.png)
?

**Comment by popaula937** [comment]
Hi, are you sure the path to your local tvb-recon is correct? You say it is: **/home/nana/downloads/tvb-recon**, but in the **docker run** command, you typed: **/home/nana/downloads/tvb-recon/tvb-recon**
Same for the patients folder.

**Comment by nana-zhang** [comment]
Hello, thank you for your reply. It's true that my path is wrong. Now I have corrected it and run docker according to the instructions, but it has been running for many days, and it doesn't seem to be over yet, so I want to make sure whether it is running correctly？
/home/nana/Pictures/Screenshot from 2022-02-22 15-13-25.png

**Comment by nana-zhang** [comment]
Hello, thank you for your reply. It's true that my path is wrong. Now I have corrected it and run docker according to the instructions, but it has been running for many days, and it doesn't seem to be over yet, so I want to make sure whether it is running correctly？
![Screenshot from 2022-02-22 15-13-25](https://user-images.githubusercontent.com/70929994/155082105-19c96f36-a678-4ee9-bae5-fd73c6b1cece.png)

**Comment by popaula937** [comment]
Hi, has any new file been added to your patient folder? More specifically, have the folders **_configs_** and **_output_** been created and do they have any file inside?

**Comment by nana-zhang** [comment]
Hello, I see the generated output file as follows, but the bad thing is that I accidentally closed the terminal window of the program. If I rerun the program, will it take as long as the first time? If I didn't delete the previously generated output file
![Screenshot from 2022-02-28 15-16-30](https://user-images.githubusercontent.com/70929994/155944402-c33119e5-bceb-406a-97fb-299291449d7f.png)
![Screenshot from 2022-02-28 15-16-44](https://user-images.githubusercontent.com/70929994/155944421-25f51904-a7b5-45b3-99dd-413bc2a0d84e.png)

**Comment by nana-zhang** [comment]
Hello, I see the generated output file as follows, but the bad thing is that I accidentally closed the terminal window of the program. If I rerun the program, will it take as long as the first time? If I didn't delete the previously generated output file
![Screenshot from 2022-02-28 15-16-30](https://user-images.githubusercontent.com/70929994/155944548-e9c6437a-2967-482c-9a5e-08b280913475.png)
![Screenshot from 2022-02-28 15-16-44](https://user-images.githubusercontent.com/70929994/155944641-57a72b15-5cfc-411c-85b9-6fc4c54bf62f.png)

**Comment by nana-zhang** [comment]
Hello, I see the generated output file as follows, but the bad thing is that I accidentally closed the terminal window of the program. If I rerun the program, will it take as long as the first time? If I didn't delete the previously generated output file.
![Screenshot from 2022-02-28 15-16-30](https://user-images.githubusercontent.com/70929994/155947595-3bc1810f-83ad-49a4-acee-c0be6a846d3c.png)
![Screenshot from 2022-02-28 15-16-44](https://user-images.githubusercontent.com/70929994/155947612-e9723cbf-963a-478c-8a90-ccb1c796ed8a.png)

**Comment by nana-zhang** [comment]
Hello, I see the generated output file as follows, but the bad thing is that I accidentally closed the terminal window of the program. If I rerun the program, will it take as long as the first time? If I didn't delete the previously generated output file
![Screenshot from 2022-02-28 15-16-30](https://user-images.githubusercontent.com/70929994/155947909-bd2d4e2d-c772-4cba-86a7-96581440f56e.png)
![Screenshot from 2022-02-28 15-16-44](https://user-images.githubusercontent.com/70929994/155947920-708e224e-427b-4853-830b-8b201cde76ed.png)

**Comment by popaula937** [comment]
Hi, before re-running, what files do you have under the output/tvb folder?

**Comment by nana-zhang** [comment]
Sorry, I've run it again. The output / TVB folder is like this now. I don't know whether it's my computer or something wrong. It took more than ten days to run this code last time, and it doesn't seem to be over yet,
![Screenshot from 2022-02-28 19-32-24](https://user-images.githubusercontent.com/70929994/155976497-d91c6f54-2661-4c44-8424-ed0040f1f01e.png)

**Comment by nana-zhang** [comment]
Then I follow the instructions to query the running status of the program, which has been at% 67.4 since yesterday. Is this normal?
![Screenshot from 2022-03-01 13-09-24](https://user-images.githubusercontent.com/70929994/156108805-38d014e8-8fdd-4e75-9407-91a4369ffa5e.png)

**Comment by popaula937** [comment]
Hi, usually it does not take more than 1-2 days to run tvb-recon, depending on the data. It seems to be stuck at generating the connectome for some reason.
Is the size of 2M.tck file larger than zero?

Have you ever tried running Mrtrix on this data before? We could try to run this step separately, to check how it works.

Also, we could try to debug this together in a call, if we manage to synchronize.

**Comment by nana-zhang** [comment]
Hello, thank you for your reply. I guess it should be the problem of my computer. I changed a computer with high configuration and finished the program in one day

**Comment by popaula937** [comment]
Hi, thanks for letting us know. Could you share what were the resources of the first computer you tried?
